name: mavericscare
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  country_picker: ^2.0.26
  pinput: ^4.0.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^2.0.10+1
  mobile_scanner: ^5.1.0
  scan: ^1.6.0
  qr_flutter: ^4.1.0
  image_picker: ^1.1.1
  http: ^1.2.1
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/images/
     - assets/logo/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
    android: "launcher_icon"
    ios: "AppIcon"
    image_path: "assets/logo/logo.png"
    min_sdk_android: 21
    remove_alpha_ios: true
